### ISSUE TITLE
Uncaught Error: Class 'MWD\ComplexTitles\Init' not found in

### ISSUE THREAD

**Issue by 1ucay** [MWDelaney/acf-complex-titles#2]
I have error Uncaught Error: Class 'MWD\ComplexTitles\Init' not found, when I activate plugin. Thanks

**Comment by MWDelaney** [comment]
Hi, thank you for reporting this. Sorry it's taken me so long to get back to you.

This should be fixed in 4a16d85. I'll do some testing and make a new Release as soon as I can.
